# Generated by Django 5.2.5 on 2025-08-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=2048)),
                ('short_code', models.CharField(blank=True, db_index=True, max_length=15, unique=True)),
                ('salt', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
