# Generated by Django 5.2.5 on 2025-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
